In [1]:
import os 
import pandas as pd
import numpy as np

In [2]:
et = pd.read_csv("data/earth_temp_updated.csv")
et = et.fillna("NULL")
et['Year'] = et['dt'].str.slice(0,4)
et['Year'] = et['Year'].astype(int)
et = et[(et['Year'] > 2004) & (et['Year'] < 2014)]
et

dt AverageTemperature AverageTemperatureUncertainty  Year
2124  2005-01-01            -13.081                          0.24  2005
2125  2005-02-01             -6.682                         0.339  2005
2126  2005-03-01             -1.717                         0.276  2005
2127  2005-04-01              2.924                         0.162  2005
2128  2005-05-01              8.535                         0.141  2005
...          ...                ...                           ...   ...
2224  2013-05-01                7.8                         0.271  2013
2225  2013-06-01             11.556                         0.407  2013
2226  2013-07-01             13.366                         0.201  2013
2227  2013-08-01             13.495                         0.524  2013
2228  2013-09-01             10.332                         2.327  2013

[105 rows x 4 columns]

In [3]:
sql_file = open('cpsc368_ddl4.sql', 'w')

In [4]:
## USE NAMES FROM ER DIAGRAM NO CAPS UNDERSCORES BETWEEN

for index, row in et.iterrows():
    dt = str(row["dt"])
    avgtemp = str(row['AverageTemperature'])
    avgtu = str(row['AverageTemperatureUncertainty'])
    line = 'insert into temperature values (' + "'" + dt + "'" + ', ' + avgtemp + ', ' + avgtu + ');'
    sql_file.write(line +"\n")




In [5]:
pc = pd.read_csv("data/BC_Power_Generation_updated.csv")
pc = pc[['source', 'year', 'value']]
pc = pc.rename(columns = {'year':'Year'})
pc = pc.fillna("NULL")
pc = pc[(pc['Year'] > 2004) & (pc['Year'] < 2014)]
pc

source  Year       value
0   BIOMASS / GEOTHERMAL  2005   10.308265
1            COAL & COKE  2005    0.000000
2   HYDRO / WAVE / TIDAL  2005  217.177200
3            NATURAL GAS  2005    8.578501
4                    OIL  2005    0.327802
..                   ...   ...         ...
67           NATURAL GAS  2013    5.472094
68                   OIL  2013    1.041511
69                 SOLAR  2013    0.000000
70               NUCLEAR  2013    0.000000
71                  WIND  2013    3.096000

[72 rows x 3 columns]

In [6]:
sql_file.write("\n")
sql_file.write("--now add in power generated data")

33

In [7]:
for index, row in pc.iterrows():
    source = str(row["source"])
    year = str(row['Year'])
    value = str(row['value'])
    line = 'insert into power_generated values (' + "'" + source + "'" ', ' + year + ', ' + value + ');'
    sql_file.write(line +"\n")

In [8]:
pcons = pd.read_csv("data/BC_Power_Consumed_updated (1).csv")
pcons = pcons.rename(columns = {'year':'Year'})
pcons = pcons.fillna("NULL")
pcons = pcons[(pcons['Year'] > 2004) & (pcons['Year'] < 2014)]
pcons

sector                      source  Year     value
0    TOTAL DEMAND                    HYDROGEN  2005    0.0000
1    TOTAL DEMAND                OIL PRODUCTS  2006  457.0888
2    TOTAL DEMAND                 NATURAL GAS  2007  321.0989
3    TOTAL DEMAND                 ELECTRICITY  2008  213.8629
4    TOTAL DEMAND                    HYDROGEN  2008    0.0000
5    TOTAL DEMAND  COAL, COKE & COKE OVEN GAS  2009   11.3030
6    TOTAL DEMAND                OIL PRODUCTS  2009  430.8465
7    TOTAL DEMAND  BIOFUELS & EMERGING ENERGY  2010  204.5951
8    TOTAL DEMAND                 NATURAL GAS  2010  305.5171
9    TOTAL DEMAND                 ELECTRICITY  2011  210.4740
10   TOTAL DEMAND                    HYDROGEN  2011    0.0000
11   TOTAL DEMAND  COAL, COKE & COKE OVEN GAS  2012    7.7310
12   TOTAL DEMAND                OIL PRODUCTS  2012  410.1219
13   TOTAL DEMAND  BIOFUELS & EMERGING ENERGY  2013  207.3535
14   TOTAL DEMAND                 NATURAL GAS  2013  361.7364
67   TOTAL DEMAND  COAL, COKE & COKE OVEN GAS  2005   12.8279
68   TOTAL DEMAND                OIL PRODUCTS  2005  453.3986
69   TOTAL DEMAND  BIOFUELS & EMERGING ENERGY  2006  222.7507
70   TOTAL DEMAND                 NATURAL GAS  2006  310.0628
71   TOTAL DEMAND                 ELECTRICITY  2007  219.5540
72   TOTAL DEMAND                    HYDROGEN  2007    0.0000
73   TOTAL DEMAND  COAL, COKE & COKE OVEN GAS  2008   14.6129
74   TOTAL DEMAND                OIL PRODUCTS  2008  461.5127
75   TOTAL DEMAND  BIOFUELS & EMERGING ENERGY  2009  184.2673
76   TOTAL DEMAND                 NATURAL GAS  2009  314.4162
77   TOTAL DEMAND                 ELECTRICITY  2010  210.2545
78   TOTAL DEMAND  COAL, COKE & COKE OVEN GAS  2011   11.3390
79   TOTAL DEMAND                OIL PRODUCTS  2011  416.6552
80   TOTAL DEMAND  BIOFUELS & EMERGING ENERGY  2012  212.4715
81   TOTAL DEMAND                 NATURAL GAS  2012  358.8965
82   TOTAL DEMAND                 ELECTRICITY  2013  209.3791
135  TOTAL DEMAND  BIOFUELS & EMERGING ENERGY  2005  229.0653
136  TOTAL DEMAND                 NATURAL GAS  2005  365.9471
137  TOTAL DEMAND                 ELECTRICITY  2006  218.6680
138  TOTAL DEMAND  COAL, COKE & COKE OVEN GAS  2007   15.4189
139  TOTAL DEMAND                OIL PRODUCTS  2007  466.9429
140  TOTAL DEMAND  BIOFUELS & EMERGING ENERGY  2008  170.6639
141  TOTAL DEMAND                 NATURAL GAS  2008  321.1971
142  TOTAL DEMAND                 ELECTRICITY  2009  214.6461
143  TOTAL DEMAND  COAL, COKE & COKE OVEN GAS  2010   11.3210
144  TOTAL DEMAND                    HYDROGEN  2010    0.0000
145  TOTAL DEMAND  BIOFUELS & EMERGING ENERGY  2011  202.1806
146  TOTAL DEMAND                    HYDROGEN  2013    0.0000
209  TOTAL DEMAND                 ELECTRICITY  2005  227.7985
210  TOTAL DEMAND  COAL, COKE & COKE OVEN GAS  2006   14.3710
211  TOTAL DEMAND                    HYDROGEN  2006    0.0000
212  TOTAL DEMAND  BIOFUELS & EMERGING ENERGY  2007  212.0660
213  TOTAL DEMAND                    HYDROGEN  2009    0.0000
214  TOTAL DEMAND                OIL PRODUCTS  2010  444.8529
215  TOTAL DEMAND                 NATURAL GAS  2011  342.7726
216  TOTAL DEMAND                 ELECTRICITY  2012  209.2000
217  TOTAL DEMAND                    HYDROGEN  2012    0.0000
218  TOTAL DEMAND  COAL, COKE & COKE OVEN GAS  2013    5.4400
219  TOTAL DEMAND                OIL PRODUCTS  2013  422.6309

In [9]:
sql_file.write("\n")
sql_file.write("--now add in power consumed data")

32

In [10]:
for index, row in pcons.iterrows():
    source = str(row["source"])
    year = str(row['Year'])
    value = str(row['value'])
    line = 'insert into power_consumed values (' + "'" + source + "'" + ', ' + year + ', ' + value + ');'
    sql_file.write(line +"\n")

In [11]:
precip = pd.read_csv("data/Station_data_cleaned_updated.csv")
precip['MAX_TEMP'] = precip['MAX_TEMP'].replace(' None', np.nan)
precip['MAX_TEMP'] = precip['MAX_TEMP'].astype(float)
precip['ONE_DAY_PRECIPITATION'] = precip['ONE_DAY_PRECIPITATION'].replace(' None', np.nan)
precip['ONE_DAY_PRECIPITATION'] = precip['ONE_DAY_PRECIPITATION'].astype(float)
precip = precip.fillna("NULL")
precip = precip[(precip['Year'] > 2004) & (precip['Year'] < 2014)]
precip.dtypes

ONE_DAY_PRECIPITATION     object
MIN_TEMP                 float64
MAX_TEMP                  object
Station                   object
Year                       int64
Month                      int64
dtype: object

In [12]:
sql_file.write("\n")
sql_file.write("--now add in precipitation data")

31

In [13]:
for index, row in precip.iterrows():
    station = str(row["Station"])
    year = str(row['Year'])
    month = str(row['Month'])
    mintemp = str(row['MIN_TEMP'])
    maxtemp = str(row['MAX_TEMP'])
    pre = str(row['ONE_DAY_PRECIPITATION'])
    line = 'insert into precipitation values (' + "'" + station + "'" + ', ' + year + ', ' + month + ', ' + maxtemp + ', ' + mintemp + ', ' + pre +');'
    sql_file.write(line +"\n")

In [14]:
pop_data = pd.read_csv("data/BC_Population_2005-2002_updated.csv")

pop_pg = pop_data.merge(pc, on = 'Year')
pop_pgc = pop_pg.merge(pcons, on = 'Year')
pop_pgc = pop_pgc.fillna("NULL")
pop_pgc = pop_pgc.drop_duplicates(['Year', 'Region'])
pop_pgc = pop_pgc[(pop_pgc['Year'] > 2004) & (pop_pgc['Year'] < 2014)]
pop_pgc

Region                          Municipality  Year    Total  \
0        1003                               Elkford  2005    2,550   
48       1006                              Sparwood  2005    3,734   
96       1012                                Fernie  2005    4,383   
144      1022                             Cranbrook  2005   18,770   
192      1028                             Kimberley  2005    6,315   
...       ...                                   ...   ...      ...   
82272    9027                  Harrison Hot Springs  2013    1,435   
82320    9032                                  Kent  2013    5,877   
82368    9052                            Abbotsford  2013  140,168   
82416    9056                               Mission  2013   38,213   
82464    9999  Unincorporated Areas - Fraser Valley  2013   17,604   

                   source_x    value_x        sector  \
0      BIOMASS / GEOTHERMAL  10.308265  TOTAL DEMAND   
48     BIOMASS / GEOTHERMAL  10.308265  TOTAL DEMAND   
96     BIOMASS / GEOTHERMAL  10.308265  TOTAL DEMAND   
144    BIOMASS / GEOTHERMAL  10.308265  TOTAL DEMAND   
192    BIOMASS / GEOTHERMAL  10.308265  TOTAL DEMAND   
...                     ...        ...           ...   
82272  BIOMASS / GEOTHERMAL  13.758844  TOTAL DEMAND   
82320  BIOMASS / GEOTHERMAL  13.758844  TOTAL DEMAND   
82368  BIOMASS / GEOTHERMAL  13.758844  TOTAL DEMAND   
82416  BIOMASS / GEOTHERMAL  13.758844  TOTAL DEMAND   
82464  BIOMASS / GEOTHERMAL  13.758844  TOTAL DEMAND   

                         source_y   value_y  
0                        HYDROGEN    0.0000  
48                       HYDROGEN    0.0000  
96                       HYDROGEN    0.0000  
144                      HYDROGEN    0.0000  
192                      HYDROGEN    0.0000  
...                           ...       ...  
82272  BIOFUELS & EMERGING ENERGY  207.3535  
82320  BIOFUELS & EMERGING ENERGY  207.3535  
82368  BIOFUELS & EMERGING ENERGY  207.3535  
82416  BIOFUELS & EMERGING ENERGY  207.3535  
82464  BIOFUELS & EMERGING ENERGY  207.3535  

[1719 rows x 9 columns]

In [15]:
sql_file.write("\n")
sql_file.write("--now add in population data")

28

In [16]:
for index, row in pop_pgc.iterrows():
    sourcepg = str(row["source_x"])
    sourcepc = str(row['source_y'])
    year = str(row['Year'])
    region = str(row['Region'])
    munic = str(row['Municipality'])
    total = str(row['Total'])
    line = 'insert into population values (' + year + ', ' + region + ', ' + "'" + munic + "'" + ',' + "'" + total + "'" + ',' + "'" + sourcepg + "'" + ',' + year + ',' + "'" + sourcepc + "'" + ',' + year + ');'
    sql_file.write(line +"\n")

In [17]:
temp_pc = pc.merge(et, on = 'Year')
temp_pc = temp_pc.fillna("NULL")
print(temp_pc['Year'].unique())
temp_pc

[2005 2006 2007 2008 2009 2010 2011 2012 2013]


source  Year      value          dt  AverageTemperature  \
0    BIOMASS / GEOTHERMAL  2005  10.308265  2005-01-01             -13.081   
1    BIOMASS / GEOTHERMAL  2005  10.308265  2005-02-01              -6.682   
2    BIOMASS / GEOTHERMAL  2005  10.308265  2005-03-01              -1.717   
3    BIOMASS / GEOTHERMAL  2005  10.308265  2005-04-01               2.924   
4    BIOMASS / GEOTHERMAL  2005  10.308265  2005-05-01               8.535   
..                    ...   ...        ...         ...                 ...   
835                  WIND  2013   3.096000  2013-05-01               7.800   
836                  WIND  2013   3.096000  2013-06-01              11.556   
837                  WIND  2013   3.096000  2013-07-01              13.366   
838                  WIND  2013   3.096000  2013-08-01              13.495   
839                  WIND  2013   3.096000  2013-09-01              10.332   

     AverageTemperatureUncertainty  
0                            0.240  
1                            0.339  
2                            0.276  
3                            0.162  
4                            0.141  
..                             ...  
835                          0.271  
836                          0.407  
837                          0.201  
838                          0.524  
839                          2.327  

[840 rows x 6 columns]

In [18]:
sql_file.write("\n")
sql_file.write("--now add in influences_temp_power_generated data")

49

In [19]:
for index, row in temp_pc.iterrows():
    date = str(row["dt"])
    year = str(row['Year'])
    source = str(row['source'])
    line = 'insert into influences_temp_power_generated values (' "'" + date + "'" + ',' +  year + ',' + "'" + source + "'" +  ');'
    sql_file.write(line +"\n")

In [20]:
temp_precip = et.merge(precip, on = 'Year')
temp_precip = temp_precip.fillna("NULL")
print(temp_precip['Year'].unique())
temp_precip

[2005 2006 2007 2008 2009 2010 2011 2012 2013]


dt  AverageTemperature  AverageTemperatureUncertainty  Year  \
0      2005-01-01             -13.081                          0.240  2005   
1      2005-01-01             -13.081                          0.240  2005   
2      2005-01-01             -13.081                          0.240  2005   
3      2005-01-01             -13.081                          0.240  2005   
4      2005-01-01             -13.081                          0.240  2005   
...           ...                 ...                            ...   ...   
97327  2013-09-01              10.332                          2.327  2013   
97328  2013-09-01              10.332                          2.327  2013   
97329  2013-09-01              10.332                          2.327  2013   
97330  2013-09-01              10.332                          2.327  2013   
97331  2013-09-01              10.332                          2.327  2013   

      ONE_DAY_PRECIPITATION  MIN_TEMP MAX_TEMP Station  Month  
0                       0.0     -18.0    -12.0     MIS      1  
1                       0.1      -4.8     -1.2     MIS      2  
2                       0.0      -3.4      5.1     MIS      3  
3                      14.0      -8.7     -2.3     MIS      4  
4                       0.0      -2.5     12.0     MIS      5  
...                     ...       ...      ...     ...    ...  
97327                   0.0      10.0     25.4     PRS      8  
97328                   0.0       7.1     22.9     PRS      9  
97329                   8.4       4.2      7.8     PRS     10  
97330                   0.0      -4.9      5.5     PRS     11  
97331                  17.2     -15.9      0.5     PRS     12  

[97332 rows x 9 columns]

In [21]:
sql_file.write("\n")
sql_file.write("--now add in influences_temp_precipitation data")

47

In [22]:
for index, row in temp_precip.iterrows():
    date = str(row["dt"])
    year = str(row['Year'])
    station = str(row['Station'])
    month = str(row['Month'])
    line = 'insert into influences_temp_precipitation values (' "'" + date + "'" + ',' + "'" + station + "'" + ',' +  year + ',' + "'" + month + "'" +  ');'
    sql_file.write(line +"\n")

In [23]:
temp_pcons = et.merge(pcons, on = 'Year')
temp_pcons = temp_pcons.fillna("NULL")
print(temp_pcons['Year'].unique())
temp_pcons

[2005 2006 2007 2008 2009 2010 2011 2012 2013]


dt  AverageTemperature  AverageTemperatureUncertainty  Year  \
0    2005-01-01             -13.081                          0.240  2005   
1    2005-01-01             -13.081                          0.240  2005   
2    2005-01-01             -13.081                          0.240  2005   
3    2005-01-01             -13.081                          0.240  2005   
4    2005-01-01             -13.081                          0.240  2005   
..          ...                 ...                            ...   ...   
625  2013-09-01              10.332                          2.327  2013   
626  2013-09-01              10.332                          2.327  2013   
627  2013-09-01              10.332                          2.327  2013   
628  2013-09-01              10.332                          2.327  2013   
629  2013-09-01              10.332                          2.327  2013   

           sector                      source     value  
0    TOTAL DEMAND                    HYDROGEN    0.0000  
1    TOTAL DEMAND  COAL, COKE & COKE OVEN GAS   12.8279  
2    TOTAL DEMAND                OIL PRODUCTS  453.3986  
3    TOTAL DEMAND  BIOFUELS & EMERGING ENERGY  229.0653  
4    TOTAL DEMAND                 NATURAL GAS  365.9471  
..            ...                         ...       ...  
625  TOTAL DEMAND                 NATURAL GAS  361.7364  
626  TOTAL DEMAND                 ELECTRICITY  209.3791  
627  TOTAL DEMAND                    HYDROGEN    0.0000  
628  TOTAL DEMAND  COAL, COKE & COKE OVEN GAS    5.4400  
629  TOTAL DEMAND                OIL PRODUCTS  422.6309  

[630 rows x 7 columns]

In [24]:
sql_file.write("\n")
sql_file.write("--now add in influences_temp_power_consumed data")

48

In [25]:
for index, row in temp_pcons.iterrows():
    date = str(row["dt"])
    year = str(row['Year'])
    source = str(row['source'])
    line = 'insert into influences_temp_power_consumed values (' "'" + date + "'" + ',' + "'" + source + "'" + ',' +  year  +  ');'
    sql_file.write(line +"\n")

In [26]:
pcons_precip = precip.merge(pcons, on = 'Year')
pcons_precip = pcons_precip.fillna("NULL")
print(pcons_precip['Year'].unique())
pcons_precip

[2005 2006 2007 2008 2009 2010 2011 2012 2013]


ONE_DAY_PRECIPITATION  MIN_TEMP MAX_TEMP Station  Year  Month  \
0                       0.0     -18.0    -12.0     MIS  2005      1   
1                       0.0     -18.0    -12.0     MIS  2005      1   
2                       0.0     -18.0    -12.0     MIS  2005      1   
3                       0.0     -18.0    -12.0     MIS  2005      1   
4                       0.0     -18.0    -12.0     MIS  2005      1   
...                     ...       ...      ...     ...   ...    ...   
50047                  17.2     -15.9      0.5     PRS  2013     12   
50048                  17.2     -15.9      0.5     PRS  2013     12   
50049                  17.2     -15.9      0.5     PRS  2013     12   
50050                  17.2     -15.9      0.5     PRS  2013     12   
50051                  17.2     -15.9      0.5     PRS  2013     12   

             sector                      source     value  
0      TOTAL DEMAND                    HYDROGEN    0.0000  
1      TOTAL DEMAND  COAL, COKE & COKE OVEN GAS   12.8279  
2      TOTAL DEMAND                OIL PRODUCTS  453.3986  
3      TOTAL DEMAND  BIOFUELS & EMERGING ENERGY  229.0653  
4      TOTAL DEMAND                 NATURAL GAS  365.9471  
...             ...                         ...       ...  
50047  TOTAL DEMAND                 NATURAL GAS  361.7364  
50048  TOTAL DEMAND                 ELECTRICITY  209.3791  
50049  TOTAL DEMAND                    HYDROGEN    0.0000  
50050  TOTAL DEMAND  COAL, COKE & COKE OVEN GAS    5.4400  
50051  TOTAL DEMAND                OIL PRODUCTS  422.6309  

[50052 rows x 9 columns]

In [27]:
sql_file.write("\n")
sql_file.write("--now add in influences_precipitation_power_consumed data")

57

In [ ]:
for index, row in pcons_precip.iterrows():
    month = str(row["Month"])
    year = str(row['Year'])
    station = str(row['Station'])
    source = str(row['source'])
    line = 'insert into influences_temp_power_consumed values (' + year + ',' + "'" + source + "'" + ',' + "'" + station + '"' + ',' +  year  + ',' + month +   ');'
    sql_file.write(line +"\n")

In [ ]:
sql_file.close()